### ISSUE TITLE
Change the default branch to gh-pages

### ISSUE THREAD

**Issue by PragTob** [codecurious-bln/basic-curriculum#12]
The master branch is outdated as far as I can tell. the gh-pages branch seems to be the new hotness. E.g. it'd be good to make it the default branch for everyone to see (and not miss that like I did). E.g. default branch is the branch shown when you visit this repository on github.

Everyone alright with that?

**Comment by plexus** [comment]
:+1:

**Comment by PragTob** [comment]
seems @schultyy already did that

**Comment by schultyy** [comment]
actually @NerdBabe did ;)
