### ISSUE TITLE
RailsInstaller - Support for Rails 4

### ISSUE THREAD

**Issue by schultyy** [codecurious-bln/basic-curriculum#3]
I just openend an issue in the RailsInstaller repository and asked when they plan to support Rails 4.
https://github.com/railsinstaller/railsinstaller-nix/issues/20

**Comment by schultyy** [comment]
They have some legal issues and currently on hold.

**Comment by PragTob** [comment]
They are but you can generally just do `gem install rails` (or update) which will update and work.

**Comment by PragTob** [comment]
Also the [installfest guide from railsbridge](http://installfest.railsbridge.org/installfest/choose_your_operating_system) is SUPERB!

Also don't forget about [nitrous.io](https://www.nitrous.io/) for emergencies.
