### ISSUE TITLE
Fix picture_url

### ISSUE THREAD

**Issue by lislis** [codecurious-bln/basic-curriculum#30]
In the attendee tutorial url `<%= image_tag(@attendee.picture_url, :width => 600) if @attendee.picture.present? %>` should be changed to `<%= image_tag(@attendee.picture, :width => 600) if @attendee.picture.present? %>`

**Comment by lislis** [comment]
Or maybe not? I'm confused.....

**Comment by plexus** [comment]
the carrierwave README also uses `_url`, so it's definitely not wrong 

https://github.com/carrierwaveuploader/carrierwave

``` erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <p>
    <label>My Avatar URL:</label>
    <%= image_tag(@user.avatar_url) if @user.avatar? %>
    <%= f.text_field :remote_avatar_url %>
  </p>
<% end %>
```

**Comment by lislis** [comment]
An attendee had problems with this but that problem just disappeared. Weird, I'm closing it for now

**Comment by schultyy** [comment]
We also had problems with this one but in our case it turned out that a file was not saved :)
