### ISSUE TITLE
Gmaps4Rails does not work

### ISSUE THREAD

**Issue by schultyy** [codecurious-bln/basic-curriculum#4]
As Tobi already mentioned the google map does not appear in the browser. 
Developer console:

```
Uncaught ReferenceError: Gmaps is not defined 
```

**Comment by ellenkoenig** [comment]
Not sure if that helps, but this issue already appeared (for some students) during the last workshop using the then current Rails version. During the WS time, we could not figure out what was the reasons, so our workaround at the time was to add some manual CSS styling somewhere (unfortunately I don't remember the details, but it wasn't an elegant solution anyway).

**Comment by PragTob** [comment]
Under which circumstances? Could you please be a bit more specific, it should work with the old rails version at least... so a link to an app pushed to github or something would help. Could be anything from gem not installed, server not restarted, script not included etc...

**Comment by plexus** [comment]
If it only required some CSS changes, then maybe it's the issue I
encountered while trying out the tutorial on Rails 4. I had to manually set
the height of div#map, it had a zero height, so it was invisible.

**Comment by ellenkoenig** [comment]
I assume it is the same issue that @plexus faced. It was definately not related to  gems missing, server not being restarted, script missing etc. All that was missing was a CSS setting to make the map visible (it had zero height set) The code is on the students laptop, so I don't have access  to it.

**Comment by jmentz** [comment]
We had the same problem at the danish workshop in Aarhus. The map has also not been displayed. We also fixed it by applying that style.

**Comment by plexus** [comment]
So we can consider this confirmed :)

I'm guessing Gmaps4Rails intends to inject some CSS into the asset
pipeline, but somehow doesn't. Something to look in to and report upstream.

**Comment by PragTob** [comment]
It always worked beautifully for me, also at my university course. So either it's a new version or some other weird stuff...

**Comment by plexus** [comment]
You need to add

```
<%= stylesheet_link_tag 'gmaps4rails' %>
```

To the layout. That's mentioned in the GMaps4Rails README, but not in the
tutorial.

I can make a PR, but I'd like to convert the HTML files to Markdown, I'll
look into that first.

**Comment by plexus** [comment]
Opening a separate issue for the HTML vs Markdown discussion.
