### ISSUE TITLE
Automate HTML generation and publishing

### ISSUE THREAD

**Issue by plexus** [codecurious-bln/basic-curriculum#7]
The HTML that is in the repo seems to not be hand-written, and editing it is not very pleasant.

An easy solution would be to convert everything to Markdown from which we can generate the HTML. But I'd like to also talk here about how these files are published. 

I'm guessing from the file names that someone copy pastes them to Wordpress? Is this something we can automate?

Having it automated will ensure that updates quickly make it to the website.

**Comment by schultyy** [comment]
Ute copied these files manually from wordpress.

**Comment by PragTob** [comment]
So how about we make the tutorial a github pages page with jekyll? We could link that from the RailsGirlsBerlin page... always putting it into wordpress sounds troublsome.

Then the tutorial would also immediately update when we merge PRs etc. with no manual work involved.

**Comment by schultyy** [comment]
Sounds good. That definitely would it make easier to update the tutorial

**Comment by nanoparsec** [comment]
this is what i told arne on friday. we used wordpress because we had not much time. i would be happy to migrate to github pages.

ute

sent on the run. please don't mind typos.

Am 18.08.2013 um 11:16 schrieb Tobias Pfeiffer notifications@github.com:

**Comment by schultyy** [comment]
I started converting the tutorial to jekyll in a fork of this repository. I converted all steps but there is some work needed on styling.

**Comment by schultyy** [comment]
I pushed my changes to gh-pages. @NerdBabe can you check in repository settings if something needs to be adjusted for github pages?
