### ISSUE TITLE
Step 6 needs updating for gmaps4rails 2.0.0

### ISSUE THREAD

**Issue by phansch** [codecurious-bln/basic-curriculum#9]
It seems that the new version of gmaps4rails is a complete rewrite. [Step 6](http://railsgirlsberlin.de/apptutorial/rails-girls-app-tutorial-step-6/) will probably need to be rewritten to reflect that, as it is not working right now. We ran into the problem in todays hackday.

Everything after (and including) `rails generate gmaps4rails:install` isn't working.

**Comment by jmentz** [comment]
Hi Philipp,

thanks a lot for your hint! 

I just opened pull request https://github.com/RailsGirlsBerlin/basic-curriculum/pull/10 to fix the curriculum.

Best regards
Johannes

**Comment by jmentz** [comment]
Pull request has been merged, therefore i close that issue.
